config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('uzum_copy.urls')),
    path('users/', include('users.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import main_pag, register_view, login_view, logout_view, profile_view, edit_profile_view, add_coins_view

app_name = 'users'

urlpatterns = [
    path('', main_pag, name='mainpag'),
    path('sighnup/', register_view, name='sighnup'),
    # path('sighin/',sighnin_view, name='sighnin' ),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/', profile_view, name='profile'),
    path('edit/<int:pk>/', edit_profile_view, name='edit'),
    path('edit/<int:id>/', add_coins_view, name='add-coins'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomerUser(AbstractUser):
    ROLES = (
            ('admin', 'admin'),
            ('student', 'student'),
            ('teacher', 'teacher')
    )
    avatar = models.ImageField(upload_to='user_avatars/')
    phone_number = models.CharField(max_length=20, unique=True)
    role = models.CharField(max_length=10, choices=ROLES, default='student')
    coins = models.IntegerField(default=0)
    group = models.ForeignKey('Group', on_delete=models.CASCADE, related_name='student_group')

    def set_password(self, raw_password):
        super().set_password(raw_password)

    def __str__(self):
        return self.username

class Group(models.Model):
        DAYS = (
            ('Odd', 'Odd'),
            ('Even', 'Even'),
            ('Weekend', 'Weekend')
        )
        name = models.CharField(max_length=50)
        # members = models.ManyToManyField(CustomUser)
        teacher = models.ForeignKey(CustomerUser, on_delete=models.CASCADE, related_name='teacher')
        day = models.CharField(max_length=10, choices=DAYS)
        time = models.TimeField(default='09:00')
        created_at = models.DateTimeField(auto_now_add=True)
        updated_at = models.DateTimeField(auto_now=True)
        is_active = models.BooleanField(default=True)

        def __str__(self):
            return self.name

users/forms.py
from django.forms import ModelForm
from .models import CustomerUser


class Sighn_up_Form(ModelForm):
    class Meta:
        model = CustomerUser
        fields = ('username', 'first_name', 'last_name', 'email', 'phone_number', 'avatar', 'password')



class Sign_in_Form(ModelForm):
    class Meta:
        model = CustomerUser
        fields = ('username', 'password')



class Edit_form(ModelForm):
    class Meta:
        model = CustomerUser
        fields = ('username', 'first_name', 'last_name', 'email', 'phone_number', 'avatar')

users/views.py
from .models import  Group

from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt

from .forms import Sighn_up_Form, Edit_form
from .models import CustomerUser


def main_pag(request):
    products = CustomerUser.objects.all()  # SELECT * FROM Shop;
    context = {'products': products}
    return render(request, 'index.html', context)

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


# Create your views here.
def register_view(request):
    if request.method == 'POST':
        form = \
            Sighn_up_Form(request.POST, request.FILES)
        if form.is_valid():
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            phone_number = form.cleaned_data['phone_number']
            avatar = form.cleaned_data['avatar']
            password = form.cleaned_data['password']
            user = CustomerUser.objects.create_user(username=username,
                                                  first_name=first_name,
                                                  last_name=last_name,
                                                  email=email,
                                                  phone_number=phone_number,
                                                  avatar=avatar,
                                                  password=password)
            user.set_password(password)
            user.save()

            return redirect('home')
    else:
        form = Sighn_up_Form()
    return render(request, 'register.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('home')


def profile_view(request):
    data = CustomerUser.objects.get(id=request.user.id)
    if data.role == 'teacher':
        groups = Group.objects.filter(teacher=request.user)

        return render(request, 'teacher_profile.html', {'data': data, 'groups':groups})
    return render(request, 'profile.html', {'data': data})

def group_detail_view(request, id):
    group = Group.objects.get(id=id)
    students = CustomerUser.objects.filter(group=group, role='student')
    return render(request, 'group_detail.html', {'group': group,'students': students})


def edit_profile_view(request):
    if request.method == 'POST':
        form = Edit_form(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = Edit_form(instance=request.user)
    return render(request, 'edit_profile.html', {'form': form})


# def add_coins_view(request, id):
#     if request.method == 'POST':
#         user = CustomUser.objects.get(id=id)
#         form = request.POST
#         id = form.cleaned_data.id(request.POST)
#         coin = int(form.get('coin', 0))
#         print(coin, user)
#         user.coins += coin
#         user.save()
#         return redirect('profile')
#     return render(request, 'teacher_profile.html')

@csrf_exempt
def add_coins_view(request, id):
    if request.method == 'POST':
        try:
            user = CustomerUser.objects.get(id=id)
            coin = int(request.POST.get('coin', 0))
            user.coins += coin
            user.save()
            return JsonResponse({'success': True, 'new_coins': user.coins})
        except CustomerUser.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'User not found'})
    return JsonResponse({'success': False, 'error': 'Invalid request method'})

templates/add_product.html
{% extends 'base.html' %}
{% block content %}

    {% for product in products %}
    <div class="card ms-3 bg-dark text-white text-center" >
                <img src="{{ product.image.url }}" class="card-img-top" alt="...">
                <div class="card-body text-center">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">{{ product.price }} Coins</p>
                    <p class="card-text">{{ product.count }}</p>
                    <a href="#" class="btn btn-primary">Sotib olish</a>
                </div>
            </div>
    {% endfor %}

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mars Shop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg" style="">
    <div class="container-fluid" style="">
        <a class="navbar-brand" href="{% url 'home' %}">Main page</a>

        <button class="navbar-toggler" type="button" data-bs-toЬggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <form class="d-flex " style="margin-left: 1100px; " role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success  me-2" type="submit">Search</button>
                {% if request.user.is_authenticated %}
                <a class="btn btn-outline-warning me-2" href="{% url 'users:profile' %}">{{ request.user.username }}</a>
                <a class="btn btn-danger me-2" style="" href="{% url 'users:logout' %}">Logout</a>
                {% else %}
                <a class="btn btn-success me-2" href="{% url 'users:sighnup' %}">SignUp</a>
                <a class="btn btn-primary" href="{% url 'users:login' %}">SignIn</a>
                {% endif %}
            </form>
        </div>
    </div>
</nav>
<hr>
{% block content %}

{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

templates/edit.html
{% extends 'base.html' %}

{% block content %}

    <h1>Edit</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save changes</button>
    </form>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center">MARS Shop</h1>
<div class="цcontainer">
    <div class="row">
        {% for product in products %}
        <div class="card ms-3" style="width: 18rem;">
            <img src="{{ product.image.url }}" class="card-img-top" alt="...">
            <div class="card-body text-center">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">{{ product.price }} Coins</p>
                <p class="card-text">{{ product.count }}</p>
                <div class="container mt-4">
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#purchaseModal">
        Sotib olish
    </button>
</div>
            </div>
            <!-- Purchase Modal -->
<div class="modal fade" id="purchaseModal" tabindex="-1" aria-labelledby="purchaseModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="purchaseModalLabel">Confirmation</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            {% if message %}
            <div class="modal-body">
               <p>{{ message }}</p>
            </div>
            {% endif %}
            <div class="modal-body">
                Siz rostdan ham ushbu mahsulotni sotib olmoqchimisiz?
            </div>
            <div class="modal-footer">
                <a href="{% url 'buy' product.id %}"><button type="button" class="btn btn-success">Xa, sotib olaman</button></a>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Bekor qilish</button>

            </div>
        </div>
    </div>
</div>
        </div>


        {% endfor %}
    </div>
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}

<form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>

{% endblock %}

templates/order.html
{% extends 'base.html' %}
{% block content %}

    <form method="POST" style="text-align:center;">
        {% csrf_token %}
        <strong style="margin-bottom: 100px;">{{ form }}</strong>
        <button type="submit">Save</button>
    </form>

{% endblock %}

templates/profile.html
{% extends 'base.html' %}

{% block content %}
<header style="text-align: center;">
    <h1>User Profile</h1>
</header>
<main>
    <section class="profile-details" style="display: flex;
  justify-content: space-between; background: linear-gradient(to right, blue, green);
  width: 100%;
  height: 100vh;">
        <div class="avatar" style="width: 600px;">
            <img src="{{ data.avatar.url }}" class="" style="width: 400px; margin-left: 150px; margin-top: 100px;"
                 alt="...">
            <h2><strong>Username: </strong>{{ data.username }}</h2>
            <h2>🪙Coins: {{ data.coins }}</h2>
        </div>
        <div class="information" style="width: 481px; margin-top: 250px; margin-right: 150px;">
            <h2><strong>Firstname: </strong>{{ data.first_name }}</h2>
            <h2><strong>Lastname: </strong>{{ data.last_name }}</h2>
            <h2><strong>Email:</strong>{{ data.email }}</h2>
            <h2><strong>Phone number: </strong>{{ data.phone_number }}</h2>
            <a href="{% url 'users:edit' user.pk %}">
                <button type="submit">Edit</button>

            </a>
        </div>
    </section>
</main>


{% endblock %}

templates/signin.html
{% extends 'base.html' %}

{% block content %}

<form method="post">
        {% csrf_token %}
        {{ login_form.as_p }}
        <button type="submit">Login</button>
    </form>

{% endblock %}

templates/teacher_profile.html
{% extends 'base.html' %}

{% block content %}

  <h1>Teacher profile</h1>

  <h3>{{ data.username }}</h3>

  {% for group in groups %}
  <ul class="row">
    <li class="col-md-3 list-item d-inline">
      <div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{ group.name }}</h5>
<a href="{% url 'group-detail' group.id %}" class="btn btn-primary">Guruhga o'tish</a>
  </div>
</div>
    </li>
  </ul>
  {% endfor %}


{% endblock %}

templates/users.html
{% extends 'base.html' %}
{% block content %}

<form method="POST" enctype="multipart/form-data" style="text-align:center; background-color: black; color: white; height:720px;">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">save</button>
</form>

{% endblock %}